version: '3.8'

services:
  kafka:
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - .:/opt/jboss/keycloak/imports

  mongodb:
    container_name: filterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
  mysql:
    image: mysql
    container_name: maintenancedb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=maintenancedb
      - MYSQL_USER=mysql
      - MYSQL_TCP_PORT=3307
      - VIRTUAL_PORT=3307
    ports:
      - '3307:3307'
    expose:
      - 3307
    volumes:
      - mysqldb_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: invoicedb
    environment:
      - transport.host=localhost
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      esnet:

volumes:
  kafka_data:
  mongodb_data:
  mysqldb_data:
  keycloakdb_data:
  esdata1:
networks:
  esnet:
