global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'filter-service'
    scrape_interval: 2s
    metrics_path: '/filter-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]
  - job_name: 'inventory-service'
    scrape_interval: 2s
    metrics_path: '/inventory-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]
  - job_name: 'invoice-service'
    scrape_interval: 2s
    metrics_path: '/invoice-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]
  - job_name: 'maintenance-service'
    scrape_interval: 2s
    metrics_path: '/maintenance-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]
  - job_name: 'payment-service'
    scrape_interval: 2s
    metrics_path: '/payment-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]
  - job_name: 'rental-service'
    scrape_interval: 2s
    metrics_path: '/rental-service/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:9010' ]